* Makeblog --- The Advertising
  Makeblog is yet-simple static site generator. Generates pages from plain text
  files. Syntax is, as much as possible, visually identical to the outcome
  (actually, it's a simplified org-mode syntax).

  Features:
  1. *Editor-agnostic*: text format is suited for editing without any special
     mode.
  2. Completelly *off-line* site generation.
  3. Easily *extendable* by writing own makefiles.
  4. *Damn simple syntax* for pages.
  5. Moronic *templates*. (I "designed" them for myself.)
  6. Automatic *Atom feed* generation.
  7. Superficially "geeky" (using <code>make</code> to compile a site, isn't it?)
  
  Installation and syntax will be posted on wiki anytime soon.

* Requirements
  1. [[http://www.gnu.org/software/make/][GNU Make]], other implementations are not tested,
  2. Python,
  3. [[http://pyparsing.wikispaces.com/][pyparsing]] library.
  All three should be available in any Linux distribution. (At least I found 
  them on Ubuntu and Arch Linux.)
  
* Sample site
  It's working! I'm quite happy to use it for my site (it's in Polish):
  http://longstandingbug.com, You can see the bowels here:
  http://github.com/santamon/santamon.github.com.

* Quick start for Hardcores (until there are some installation instructions)
  Grab sources from here, then look at the <code>Makefile</code>
  and <code>config</code> files from my site. They will give you a clue.

  Then, there is the *Syntax.txt* file in input dir wich explains
  the syntax in a messy fasion.
